// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static String _envRequired(String key) {
    final value = dotenv.maybeGet(key);
    if (value == null || value.isEmpty) {
      throw StateError('Missing required env key: $key');
    }
    return value;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _envRequired('FIREBASE_WEB_API_KEY'),
    appId: '1:639324586854:web:78ba9195089eab80503ea7',
    messagingSenderId: '639324586854',
    projectId: 'kototinder-lazareva',
    authDomain: 'kototinder-lazareva.firebaseapp.com',
    storageBucket: 'kototinder-lazareva.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _envRequired('FIREBASE_ANDROID_API_KEY'),
    appId: '1:210734904100:android:ef3b519c01d521cc38f9b1',
    messagingSenderId: '210734904100',
    projectId: 'kototinder-e2f84',
    storageBucket: 'kototinder-e2f84.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _envRequired('FIREBASE_IOS_API_KEY'),
    appId: '1:210734904100:ios:d12dd4828d7704aa38f9b1',
    messagingSenderId: '210734904100',
    projectId: 'kototinder-e2f84',
    storageBucket: 'kototinder-e2f84.firebasestorage.app',
    iosBundleId: 'com.aleksandra.kototinder',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _envRequired('FIREBASE_MACOS_API_KEY'),
    appId: '1:639324586854:ios:b1e0922667087773503ea7',
    messagingSenderId: '639324586854',
    projectId: 'kototinder-lazareva',
    storageBucket: 'kototinder-lazareva.firebasestorage.app',
    iosBundleId: 'com.example.kototinder',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: _envRequired('FIREBASE_WINDOWS_API_KEY'),
    appId: '1:639324586854:web:724582138ca202cc503ea7',
    messagingSenderId: '639324586854',
    projectId: 'kototinder-lazareva',
    authDomain: 'kototinder-lazareva.firebaseapp.com',
    storageBucket: 'kototinder-lazareva.firebasestorage.app',
  );
}
