// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfHraYaDttHzTxLrSmPnwIUuRH54Kr4n0',
    appId: '1:639324586854:web:78ba9195089eab80503ea7',
    messagingSenderId: '639324586854',
    projectId: 'kototinder-lazareva',
    authDomain: 'kototinder-lazareva.firebaseapp.com',
    storageBucket: 'kototinder-lazareva.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2S4UAGLa_vGRTaZuKk0T4bsfwfk9NPE4',
    appId: '1:639324586854:android:49e6b7db4e505935503ea7',
    messagingSenderId: '639324586854',
    projectId: 'kototinder-lazareva',
    storageBucket: 'kototinder-lazareva.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABYzkF_tBXX_MbI1q3fJ0V-P8HkBE4fy4',
    appId: '1:639324586854:ios:e818341833ed37d3503ea7',
    messagingSenderId: '639324586854',
    projectId: 'kototinder-lazareva',
    storageBucket: 'kototinder-lazareva.firebasestorage.app',
    iosBundleId: 'com.aleksandra.kototinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABYzkF_tBXX_MbI1q3fJ0V-P8HkBE4fy4',
    appId: '1:639324586854:ios:b1e0922667087773503ea7',
    messagingSenderId: '639324586854',
    projectId: 'kototinder-lazareva',
    storageBucket: 'kototinder-lazareva.firebasestorage.app',
    iosBundleId: 'com.example.kototinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfHraYaDttHzTxLrSmPnwIUuRH54Kr4n0',
    appId: '1:639324586854:web:724582138ca202cc503ea7',
    messagingSenderId: '639324586854',
    projectId: 'kototinder-lazareva',
    authDomain: 'kototinder-lazareva.firebaseapp.com',
    storageBucket: 'kototinder-lazareva.firebasestorage.app',
  );
}
